export const CLUB_LOGIN = "CLUB_LOGIN";
export const CLUB_FORM_SUBMIT = "CLUB_FORM_SUBMIT";
export const CLUB_REQUESTS = "CLUB_REQUESTS";
export const CLUB_DRAFT_SUBMIT = "CLUB_DRAFT_SUBMIT";
export const CLUB_DRAFT_REQUEST = "CLUB_DRAFT_REQUEST";
export const CLUB_UPDATE_DRAFT = "CLUB_UPDATE_DRAFT";
